# Generated by Django 3.2.25 on 2025-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarcard',
            name='status',
            field=models.CharField(default='pending', max_length=500),
        ),
        migrations.AlterField(
            model_name='licence',
            name='status',
            field=models.CharField(default='pending', max_length=500),
        ),
        migrations.AlterField(
            model_name='rationcard',
            name='status',
            field=models.CharField(default='pending', max_length=500),
        ),
        migrations.AlterField(
            model_name='voterid',
            name='status',
            field=models.CharField(default='pending', max_length=500),
        ),
    ]
