# Generated by Django 3.2.25 on 2025-03-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applyalphacard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyalphacard',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='applyalphacard',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applyalphacard',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='applyalphacard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='applyalphacard',
            name='phone',
        ),
        migrations.AddField(
            model_name='applyalphacard',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applyalphacard',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applyalphacard',
            name='description',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
