# Generated by Django 3.2.25 on 2025-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250318_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyalphacard',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
