# Generated by Django 3.2.25 on 2025-03-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_applyalphacard_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applyalphacard',
            new_name='Applyalphacard_request',
        ),
    ]
