# Generated by Django 3.2.25 on 2025-03-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_applyalphacard_applyalphacard_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alphacard',
            old_name='status',
            new_name='alphanumber',
        ),
    ]
