# Generated by Django 3.2.25 on 2025-03-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_status_alphacard_alphanumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphacard',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
