# Generated by Django 3.2.25 on 2025-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_alphacard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
