# Generated by Django 3.2.25 on 2025-03-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
