# Generated by Django 3.2.25 on 2025-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20250320_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcard',
            name='FamilyMember',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
