# Generated by Django 3.2.25 on 2025-04-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rationcard_familymember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationcard',
            name='FamilyMember',
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('rationcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='app.rationcard')),
            ],
        ),
    ]
