# Generated by Django 3.2.25 on 2025-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20250405_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
