# Generated by Django 3.2.25 on 2025-04-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20250405_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphacard',
            name='AADHAARCARD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aadhaarcard'),
        ),
        migrations.AlterField(
            model_name='alphacard',
            name='LICENCE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.licence'),
        ),
        migrations.AlterField(
            model_name='alphacard',
            name='RATION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rationcard'),
        ),
        migrations.AlterField(
            model_name='alphacard',
            name='VOTERID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.voterid'),
        ),
    ]
