# Generated by Django 3.2.25 on 2025-05-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='USER',
        ),
    ]
