# Generated by Django 3.2.25 on 2025-05-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20250506_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='USER',
        ),
        migrations.AddField(
            model_name='feedback',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
            preserve_default=False,
        ),
    ]
